/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentCanceledRouteImport } from './routes/payment-canceled'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as OrderTierRouteImport } from './routes/order.$tier'
import { Route as OrdersTokenRouteImport } from './routes/orders.$token'
import { Route as ApiPublicFulfillmentTickRouteImport } from './routes/api/public/fulfillment-tick'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicDownloadTokenRouteImport } from './routes/api/public/download.$token'
import { Route as ApiPublicOrderFileTokenFileRouteImport } from './routes/api/public/order-file.$token.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledRoute = PaymentCanceledRouteImport.update({
  id: '/payment-canceled',
  path: '/payment-canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTierRoute = OrderTierRouteImport.update({
  id: '/order/$tier',
  path: '/order/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersTokenRoute = OrdersTokenRouteImport.update({
  id: '/orders/$token',
  path: '/orders/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFulfillmentTickRoute =
  ApiPublicFulfillmentTickRouteImport.update({
    id: '/api/public/fulfillment-tick',
    path: '/api/public/fulfillment-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadTokenRoute = ApiPublicDownloadTokenRouteImport.update({
  id: '/api/public/download/$token',
  path: '/api/public/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderFileTokenFileRoute =
  ApiPublicOrderFileTokenFileRouteImport.update({
    id: '/api/public/order-file/$token/$file',
    path: '/api/public/order-file/$token/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/roast': typeof RoastRoute
  '/order/$tier': typeof OrderTierRoute
  '/orders/$token': typeof OrdersTokenRoute
  '/api/public/fulfillment-tick': typeof ApiPublicFulfillmentTickRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/order-file/$token/$file': typeof ApiPublicOrderFileTokenFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/roast': typeof RoastRoute
  '/order/$tier': typeof OrderTierRoute
  '/orders/$token': typeof OrdersTokenRoute
  '/api/public/fulfillment-tick': typeof ApiPublicFulfillmentTickRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/order-file/$token/$file': typeof ApiPublicOrderFileTokenFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/roast': typeof RoastRoute
  '/order/$tier': typeof OrderTierRoute
  '/orders/$token': typeof OrdersTokenRoute
  '/api/public/fulfillment-tick': typeof ApiPublicFulfillmentTickRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/download/$token': typeof ApiPublicDownloadTokenRoute
  '/api/public/order-file/$token/$file': typeof ApiPublicOrderFileTokenFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/roast'
    | '/order/$tier'
    | '/orders/$token'
    | '/api/public/fulfillment-tick'
    | '/api/public/stripe-webhook'
    | '/api/public/download/$token'
    | '/api/public/order-file/$token/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/roast'
    | '/order/$tier'
    | '/orders/$token'
    | '/api/public/fulfillment-tick'
    | '/api/public/stripe-webhook'
    | '/api/public/download/$token'
    | '/api/public/order-file/$token/$file'
  id:
    | '__root__'
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/roast'
    | '/order/$tier'
    | '/orders/$token'
    | '/api/public/fulfillment-tick'
    | '/api/public/stripe-webhook'
    | '/api/public/download/$token'
    | '/api/public/order-file/$token/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentCanceledRoute: typeof PaymentCanceledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  RoastRoute: typeof RoastRoute
  OrderTierRoute: typeof OrderTierRoute
  OrdersTokenRoute: typeof OrdersTokenRoute
  ApiPublicFulfillmentTickRoute: typeof ApiPublicFulfillmentTickRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicDownloadTokenRoute: typeof ApiPublicDownloadTokenRoute
  ApiPublicOrderFileTokenFileRoute: typeof ApiPublicOrderFileTokenFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-canceled': {
      id: '/payment-canceled'
      path: '/payment-canceled'
      fullPath: '/payment-canceled'
      preLoaderRoute: typeof PaymentCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$tier': {
      id: '/order/$tier'
      path: '/order/$tier'
      fullPath: '/order/$tier'
      preLoaderRoute: typeof OrderTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$token': {
      id: '/orders/$token'
      path: '/orders/$token'
      fullPath: '/orders/$token'
      preLoaderRoute: typeof OrdersTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fulfillment-tick': {
      id: '/api/public/fulfillment-tick'
      path: '/api/public/fulfillment-tick'
      fullPath: '/api/public/fulfillment-tick'
      preLoaderRoute: typeof ApiPublicFulfillmentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$token': {
      id: '/api/public/download/$token'
      path: '/api/public/download/$token'
      fullPath: '/api/public/download/$token'
      preLoaderRoute: typeof ApiPublicDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-file/$token/$file': {
      id: '/api/public/order-file/$token/$file'
      path: '/api/public/order-file/$token/$file'
      fullPath: '/api/public/order-file/$token/$file'
      preLoaderRoute: typeof ApiPublicOrderFileTokenFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentCanceledRoute: PaymentCanceledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  RoastRoute: RoastRoute,
  OrderTierRoute: OrderTierRoute,
  OrdersTokenRoute: OrdersTokenRoute,
  ApiPublicFulfillmentTickRoute: ApiPublicFulfillmentTickRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicDownloadTokenRoute: ApiPublicDownloadTokenRoute,
  ApiPublicOrderFileTokenFileRoute: ApiPublicOrderFileTokenFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
